### ISSUE TITLE
Failed to export spans. Error message: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by baasbank** [signalfx/splunk-otel-collector-chart#193] opened 2021-09-15 12:38 UTC
Started seeing this error message in our logs about 12 hours ago. Nothing has changed in our setup, so we're not quite sure why it started.

```
[opentelemetry.auto.trace 2021-09-15 12:30:06:799 +0000] [grpc-default-executor-21] WARN io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter - Failed to export spans. Error message: UNAVAILABLE: io exception
```
Anyone has any ideas what the problem might be?

**Comment by atoulme** [comment] 2021-09-15 12:43
I believe this error is thrown by your Java application. The error says that your Java application is unable to send traces to the remote endpoint it is configured with because it's not responding. Please check that the remote endpoint is live and accessible from the Java application.

**Comment by baasbank** [comment] 2021-09-16 11:59
The default port was changed to 4317. Started working again after changing the port.

**Comment by dmitryax** [comment] 2021-11-24 22:38
@baasbank looks like the issue is resolved with the updated port, I'm closing the issue. Feel free to reopen

**Closed by dmitryax** 2021-11-24 22:38 UTC
