### ISSUE TITLE
Wrong timestamp in Splunk with otel instead of fluentd

### ISSUE THREAD

**Issue by dxniel7402** [signalfx/splunk-otel-collector-chart#714] opened 2023-03-31 14:41 UTC
Hello all,

I just want to migrate from splunk-connect-for-kubernetes to here. I noticed that I have the following paragraph for fluentd:
```yaml
fluentd:
  configs:
    logs:
      gwv6:
        from:
          pod: gwv6-*
            container: gwv6
          timestampExtraction:
            format: "%Y%m%dT%H%M%S.%3N%z"
          sourcetype: syslog_gwv6
```
The `timestampExtraction` process is important to me here, without it, the timestamps are displayed incorrectly in Splunk.

Unfortunately, I can't implement this with otel, according to your example, where `timestampExtraction` is mentioned: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md#extra-files-from-host

So the question is, how can I translate this here?

**Comment by dxniel7402** [comment] 2023-04-03 16:26
I have now been able to solve our problem with my colleagues. The following is now under `logsCollection.containers.extraOperators`:

```yaml
    - id: gwv6_custom-timestamp
      type: regex_parser
      if: resource["k8s.container.name"] == "gwv6"
      parse_from: attributes.log
      regex: '^(?P<custom_timestamp>\S+)'
      timestamp:
        parse_from: attributes.custom_timestamp
        layout_type: strptime
        layout: "%Y%m%dT%H%M%S.%LZ"
```

Wasn't part of the issue, but still worth mentioning: I wanted to enable multiline logs, [but that doesn't seem to work](https://github.com/signalfx/splunk-otel-collector-chart/issues/633) if you have already enabled `extraOperators`. Therefore, this has become the solution for me, also under `extraOperators`:

```yaml
    - id: gwv6_multiline
      type: recombine
      combine_field: attributes.log
      is_first_entry: (attributes.log) matches "^(\\d{4})(\\d{2})(\\d{2})T(\\d{2})(\\d{2})(\\d{2})\\.\\d{3}Z\\s+\\[[^\\]]+\\]"
      source_identifier: resource["com.splunk.source"]
```

The next important thing for me was that I can also change the sourcetype and the index accordingly, as specifically from this container is needed. Here it gets more complicated, because you have to remove and add here:

```yaml
    - id: gwv6_remove-standard-sourcetype
      type: remove
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.sourcetype"]
    - id: gwv6_add-custom-sourcetype
      type: add
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.sourcetype"]
      value: syslog_gwv6
    - id: gwv6_remove-standard-index
      type: remove
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.index"]
    - id: gwv6_add-custom-index
      type: add
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.index"]
      value: gwv6_index
```

If someone also encounters such problems, I hope to have helped in detail :-)

**Comment by matthewmodestino** [comment] 2023-04-04 13:13
Nice work! Thanks for sharing!

Just some notes, you can likely simplify a but by not having the remove operators..the add operator should overwrite it. Have you tried that?

Also @atoulme this is not a bug, as we purposely collect the timestamp from the container engine timestamp, not whats in the log entry itself. More of a "customization" option.

@dxniel7402 out of curiosity, was the container engine timestamp that much different that the timestamp in the app log? What was the driving factor there? As they should be super close.

**Comment by dxniel7402** [comment] 2023-04-04 15:26
> Nice work! Thanks for sharing!
> 
> Just some notes, you can likely simplify a but by not having the remove operators..the add operator should overwrite it. Have you tried that?
> 
> Also @atoulme this is not a bug, as we purposely collect the timestamp from the container engine timestamp, not whats in the log entry itself. More of a "customization" option.
> 
> @dxniel7402 out of curiosity, was the container engine timestamp that much different that the timestamp in the app log? What was the driving factor there? As they should be super close.

@matthewmodestino Ah okay, I didn't know that the add operator can also overwrite. It would make sense if [it were in the documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/add.md). I'll try it out soon :smile:.

The timestamps were actually not very far from each other, however, our customers noticed it and were confused by the fact that the milliseconds differed from Splunk. Now, of course, it's not the end of the world, but it looks better when everything fits and is correct :smlie:.

**Comment by matthewmodestino** [comment] 2023-04-04 15:34
> The timestamps were actually not very far from each other, however, our customers noticed it and were confused by the fact that the milliseconds differed from Splunk. Now, of course, it's not the end of the world, but it looks better when everything fits and is correct 😄.

Yeah, that makes sense for the user for sure. We usually keep so we don't hide any delays or issues at the container engine level, but frankly that issue doesn't come up much and you could always check the logs direct on the node or in kubectl to validate that. 

Thanks again for sharing, we should probably document this as an example for users for sure.

**Comment by atoulme** [comment] 2023-04-13 23:34
Closing as fixed. Thanks!

**Closed by atoulme** 2023-04-13 23:34 UTC
Labels: Splunk Platform
