### ISSUE TITLE
Can't use the otel collector chart as a subchart

### ISSUE THREAD

**Issue by tmsdce** [signalfx/splunk-otel-collector-chart#874] opened 2023-08-04 08:26 UTC
## Description
When using this chart as a subchart, I can't generate manifests using `helm template` (I use ArgoCD which uses `helm template` behind the scene).

I noticed this behavior since the introduction of `cert-manager` and `opentelemetry-operator` as dependencies in version 0.75.0 of this chart. So for now, I stick to the 0.72.0 version of this chart.

## Steps to Reproduce
- In an empty dir, create the following `Chart.yaml` file

```
apiVersion: v2
name: test-subchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: splunk-otel-collector
  repository: https://signalfx.github.io/splunk-otel-collector-chart
  version: 0.82.0
```

- Create the following `values.yaml` file. It only contains the minimal required values to comply with the `values.schema.json` file

```
splunk-otel-collector:
  clusterName: mycluster
  splunkObservability:
    realm: eu0
    accessToken: dummy
```

- Run `helm dependency update`
- Run `helm template .`

## Expected Result

Templates should be generated correctly.

## Actual Result

Helm complains that there's a schema violation :

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- (root): Additional property opentelemetry-operator is not allowed
- (root): Additional property cert-manager is not allowed
```

The weird thing is that I never use the `opentelemetry-operator` and `cert-manager` in my `values.yaml` file. I see that you declared these dependencies using aliases, and it's as if the template parsing logic is completely ignoring those aliases is some way.

It should be noted that running `helm template .` vs `helm template -f values.yaml .` leads to different results. Explicitly setting the `-f values.yaml` option does generate the manifests (as ArgoCD is controlling the way it calls the helm cmd, it can't be easily overridden)

Finally, I tested my assumptions regarding the use of aliases. I patched the otel collector chart and disabled the use of aliases for opentelemtry-operator and cert-manager (added the correct properties in the schema, etc...). In this case, manifests generation is working fine with or without the `-f values.yaml` option. Therefore, there may be some quirks involved in the way aliases are processed.

### Chart version

v0.82.0

## Environment
Cloud: VMWare
k8s version: 1.26
OS: Ubuntu 20.04
Helm version: 3.11.3

### Chart configuration

```yaml
splunk-otel-collector:
  clusterName: mycluster
  splunkObservability:
    realm: eu0
    accessToken: dummy
```

### Log output

```shell
Error: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- (root): Additional property opentelemetry-operator is not allowed
- (root): Additional property cert-manager is not allowed
```

### Additional context

An issue has also been filed on helm side but not much progress so far https://github.com/helm/helm/issues/12100

**Comment by jvoravong** [comment] 2023-08-07 17:19
At this time, using the splunk-otel-collector-chart as a subchart is not supported. From the provided evidence, the fix should happen upstream in Helm repository code or be a feature request in this chart. Closing this ticket as it is not a bug. Feel free to file a new feature request Github issue.

**Closed by jvoravong** 2023-08-07 17:19 UTC
Labels: bug

**Comment by jvoravong** [comment] 2023-08-07 18:04
Reviewed some archived messages of mine, this is likely only an issue with older versions of Helm and not recent versions.

**Comment by tmsdce** [comment] 2023-08-08 07:36
Hello @jvoravong 
My helm version is 3.11.3 but I can also confirmed the issue with the latest version of helm 3.12.2.
I definitely think that it's bug on Helm side when using a schema with aliases and subcharts which is why I opened an issue on Helm side in the first place.

Can you at least confirm that you're experiencing the same issue using my repro ?

Also, can you clarify `At this time, using the splunk-otel-collector-chart as a subchart is not supported` ? Do you mean something specific unrelated to this issue ?

**Comment by Sartigan** [comment] 2023-10-12 21:24
I am facing the same issue. Our helm vesion is up to date. The problem only occurs while trying to add the chart as a subchart
