### ISSUE TITLE
BUG: fresh deployment on a new K8s cluster results in Collector crashloop

### ISSUE THREAD

**Issue by tigrannajaryan** [signalfx/splunk-otel-collector-chart#55] opened 2021-03-04 17:02 UTC
*Steps:*

1. New K8s cluster using Docker on Mac.
2. `helm repo add splunk-otel-collector-chart https://signalfx.github.io/splunk-otel-collector-chart` succeeded.
3. `helm install my-splunk-otel-collector --set="splunkRealm=lab0,splunkAccessToken=<redacted>,clusterName=tigran-bugbash-cluster" splunk-otel-collector-chart/splunk-otel-collector` succeeded.
4. `kubectl get pods` shows:
```
NAME                                                             READY   STATUS             RESTARTS   AGE
my-splunk-otel-collector-agent-cq7h4                             1/2     CrashLoopBackOff   2          97s
my-splunk-otel-collector-k8s-cluster-receiver-5d5b95d8ff-br28k   1/1     Running            0          97s
```
5. `kubectl logs my-splunk-otel-collector-agent-cq7h4 otel-collector` shows:
```
failed to try resolving symlinks in path "/var/log/pods/default_my-splunk-otel-collector-agent-cq7h4_8a0ce21e-11cf-4222-b0e3-8010f7469fce/otel-collector/4.log": lstat /var/log/pods/default_my-splunk-otel-collector-agent-cq7h4_8a0ce21e-11cf-4222-b0e3-8010f7469fce/otel-collector/4.log: no such file or directory
```

*Expected:*
1. No crashloop for the agent.
2. Logs can be seen.

**Comment by tigrannajaryan** [comment] 2021-03-04 17:31
@dmitryax I am not sure what am I doing wrong. Should I assign this to you?

**Comment by mjpatel1** [comment] 2021-03-25 15:10
@tigrannajaryan - I am also having same issue on my K8s cluster using docker on my Mac and on GKE as well.

1. `kubectl get pods` shows:

```
NAME                                                            READY   STATUS             RESTARTS   AGE
my-splunk-otel-collector-58dd48c698-jk6ch                       1/1     Running            0          5m5s
my-splunk-otel-collector-agent-rbdpt                            1/2     CrashLoopBackOff   5          5m6s
my-splunk-otel-collector-k8s-cluster-receiver-cf7f58c47-qwssp   1/1     Running            0          5m5s
```

2. `fluentd` container under `my-splunk-otel-collector-agent` pod works fine, although `otel-collector` container is having issue
3. `kubectl logs my-splunk-otel-collector-agent-rbdpt -c otel-collector` shows:
```
failed to try resolving symlinks in path "/var/log/pods/default_my-splunk-otel-collector-agent-rbdpt_3667c420-08ff-4c65-8182-fe46eb4b6980/otel-collector/5.log": lstat /var/log/pods/default_my-splunk-otel-collector-agent-rbdpt_3667c420-08ff-4c65-8182-fe46eb4b6980/otel-collector/5.log: no such file or directory
```

**Comment by dmitryax** [comment] 2021-04-12 03:27
Docker for mac is not currently supported. 

@maulikp-splunk could you please share more details about your GKE cluster? I tried the helm chart on GKE cluster 1.18.16-gke.502 and cannot reproduce the issue.

**Comment by dmitryax** [comment] 2021-05-20 21:54
Thanks @maulikp-splunk. I'm closing the issue then

**Closed by dmitryax** 2021-05-20 21:54 UTC
Labels: bug
